import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import * as PDFDocument from 'pdfkit';

@Injectable()
export class ExportService {
  constructor(private prisma: PrismaService) {}

  async exportToHtml(documentId: string, tenantId: string) {
    const doc = await this.prisma.document.findFirst({
      where: { id: documentId, project: { tenantId } },
      include: { project: true },
    });
    if (!doc) throw new NotFoundException('Document not found');

    const html = this.generateHtml(doc.title, doc.content, doc.project.name);
    return { html, filename: `${doc.title}.html` };
  }

  async exportToPdf(documentId: string, tenantId: string, options?: {
    pageSize?: 'A4' | 'A5' | 'LETTER';
    orientation?: 'portrait' | 'landscape';
    margin?: number;
  }) {
    const doc = await this.prisma.document.findFirst({
      where: { id: documentId, project: { tenantId } },
      include: { project: true },
    });
    if (!doc) throw new NotFoundException('Document not found');

    const pageSize = options?.pageSize || 'A4';
    const orientation = options?.orientation || 'portrait';
    const margin = options?.margin || 72; // 1 inch

    // Generate PDF buffer
    const pdfBuffer = await this.generatePdf(
      doc.title,
      doc.content,
      doc.project.name,
      { pageSize, orientation, margin }
    );

    return {
      pdf: pdfBuffer.toString('base64'),
      filename: `${doc.title}.pdf`,
      contentType: 'application/pdf',
      pageSize,
      orientation,
    };
  }

  private generatePdf(title: string, content: any, projectName: string, options: {
    pageSize: string;
    orientation: string;
    margin: number;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: options.pageSize as any,
          margins: { top: options.margin, bottom: options.margin, left: options.margin, right: options.margin },
          layout: options.orientation as any,
          info: {
            Title: title,
            Author: 'ConferencePub',
            Subject: projectName,
          },
        });

        const chunks: Buffer[] = [];
        doc.on('data', (chunk: Buffer) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Cover page
        doc.fontSize(32).fillColor('#A259FF').text(title, { align: 'center' });
        doc.moveDown();
        doc.fontSize(16).fillColor('#666').text(projectName, { align: 'center' });
        doc.moveDown(2);
        doc.fontSize(12).fillColor('#999').text('Generated by ConferencePub', { align: 'center' });
        
        doc.addPage();

        // Content pages
        const sections = content?.sections || [];
        
        if (sections.length === 0) {
          // If no sections, try to render content directly
          const textContent = content?.content || content?.text || JSON.stringify(content || '');
          doc.fontSize(12).fillColor('#000').text(textContent, {
            align: 'left',
            lineGap: 4,
          });
        } else {
          sections.forEach((section: any, index: number) => {
            if (index > 0) doc.addPage();
            
            // Section title
            doc.fontSize(18).fillColor('#333').text(section.title || '', {
              align: 'left',
            });
            
            doc.moveDown(0.5);
            
            // Section content
            doc.fontSize(12).fillColor('#000').text(section.content || '', {
              align: 'left',
              lineGap: 4,
            });

            // Images
            if (section.images?.length) {
              doc.moveDown();
              section.images.forEach((img: any) => {
                if (img.url) {
                  try {
                    doc.image(img.url, {
                      fit: [400, 300],
                      align: 'center',
                    });
                  } catch (e) {
                    // Skip invalid images
                  }
                }
              });
            }
          });
        }

        // Page numbers
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
          doc.switchToPage(i);
          doc.fontSize(10).fillColor('#999').text(
            `${i + 1}`,
            doc.page.width - 50,
            doc.page.height - 30,
            { align: 'center' }
          );
        }

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  private generateHtml(title: string, content: any, projectName: string, printMode = false): string {
    const sections = content?.sections || [];
    
    const sectionsHtml = sections.map((section: any) => {
      return `
        <section class="${section.type}">
          <h2>${this.escapeHtml(section.title || '')}</h2>
          <p>${this.escapeHtml(section.content || '').replace(/\n/g, '<br>')}</p>
        </section>
      `;
    }).join('');

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${this.escapeHtml(title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
           padding: 40px; color: #333; line-height: 1.6; }
    h1 { font-size: 28px; color: #A259FF; margin-bottom: 8px; }
    .subtitle { font-size: 14px; color: #666; margin-bottom: 32px; }
    section { margin-bottom: 24px; page-break-inside: avoid; }
    h2 { font-size: 18px; color: #333; margin-bottom: 8px; border-bottom: 2px solid #A259FF; padding-bottom: 4px; }
    p { font-size: 14px; text-align: justify; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>${this.escapeHtml(title)}</h1>
  <p class="subtitle">${this.escapeHtml(projectName)}</p>
  ${sectionsHtml || `<p>${this.escapeHtml(content?.content || '')}</p>`}
</body>
</html>`;
  }

  private escapeHtml(text: string): string {
    if (!text) return '';
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  // Batch export multiple documents
  async exportBatch(documentIds: string[], tenantId: string) {
    const results = await Promise.all(
      documentIds.map(async (id) => {
        try {
          const pdf = await this.exportToPdf(id, tenantId);
          return { id, success: true, filename: pdf.filename };
        } catch (error) {
          return { id, success: false, error: error.message };
        }
      })
    );
    return results;
  }

  // Get supported page sizes
  getPageSizes() {
    return [
      { value: 'A4', label: 'A4 (210 × 297mm)', width: 210, height: 297 },
      { value: 'A5', label: 'A5 (148 × 210mm)', width: 148, height: 210 },
      { value: 'LETTER', label: 'Letter (8.5 × 11")', width: 215.9, height: 279.4 },
    ];
  }
}
